version: "3.9"

services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@localhost:5432/
  db:
    image: postgres:13
    restart: always
    container_name: app_nation_case_study_backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: app_nation_case_study_backend_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
